[package]
name = "hayabusa"
version = "2.14.0-dev"
repository = "https://github.com/Yamato-Security/hayabusa"
authors = ["Yamato Security @SecurityYamato"]
edition = "2021"
rust-version = "1.76.0"
include = ["src/**/*", "LICENSE.txt", "README.md", "CHANGELOG.md"]

[dependencies]
aho-corasick = "*"
base64 = "*"
bytesize = "1.*"
chrono = "0.4.*"
cidr-utils = "0.5.*"
clap = { version = "4.*", features = ["derive", "cargo", "color"]}
comfy-table = "7.*"
compact_str = "0.7.*"
console = "0.15.*"
csv = "1.3.*"
dashmap = "*"
dialoguer = "*"
downcast-rs = "1.*"
evtx = { git = "https://github.com/Yamato-Security/hayabusa-evtx.git" , features = ["fast-alloc"] , rev = "e592a9a" } # 0.8.8 2024/02/18 update
git2 = "0.*"
hashbrown = "0.14.*"
hex = "0.4.*"
horrorshow = "0.8.*"
indexmap = "2.*"
indicatif = "*"
itertools = "*"
krapslog = "0.5"
lazy_static = "1.4.*"
libmimalloc-sys = { version = "*",  features = ["extended"] }
maxminddb = "0.*"
memchr = "2.*"
mimalloc = { version = "*", default-features = false }
nested="*"
num = "0.4.0"
num-format = "*"
pulldown-cmark = { version = "0.9.*", default-features = false, features = ["simd"] }
regex = "1"
serde = { version = "1.*", features = ["derive"] }
serde_derive = "1.*"
serde_json = { version = "1.0"}
termcolor = "*"
terminal_size = "*"
tokio = { version = "1", features = ["full"] }
ureq = "*"
wildmatch = "2.*"
yaml-rust = "0.4.*"

[profile.dev]
debug-assertions = false

[dev-dependencies]
rand = "0.8.*"

[target.'cfg(windows)'.dependencies]
is_elevated = "0.1.*"

[target.'cfg(unix)'.dependencies] #Mac and Linux
openssl = { version = "*", features = ["vendored"] }  #vendored is needed to compile statically.

[profile.release]
lto = true
strip = "symbols"