name: GitHub pages deploy
on:
  workflow_dispatch:

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: pip install mkdocs-material
      - run: pip install mike --force-reinstall --verbose
      - name: Build JA docs
        uses: ./
        with:
          entrypoint: mkdocs
          args: build --config-file=mkdocs.ja.yml
      - name: Build EN docs
        uses: ./
        with:
          entrypoint: mkdocs
          args: build --config-file=mkdocs.en.yml
      - name: Build docs
        uses: ./
        with:
          entrypoint: mkdocs
          args: build --config-file=mkdocs.yml
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Deploy docs to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
